[package]
name = "yaco-api"
description = "Definitions of the YACO node API: paths, and request and response types."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
utoipa.workspace = true

[dev-dependencies]
serde_json.workspace = true
