[package]
name = "yaco-agent"
description = "The single agent binary that runs on every YACO node."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "yaco-agent"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
chitchat.workspace = true
clap.workspace = true
defguard_wireguard_rs.workspace = true
hkdf.workspace = true
humantime-serde.workspace = true
ipnet.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
